name: Run Selenium Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Run smoke test
        run: mvn clean -Dtest=SmokeTest test

      - name: Verify Allure content
        run: |
          echo "Content target/allure-results:"
          ls -la target/allure-results || echo "allure-results folder is not found"

      - name: Upload Allure Results (raw)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Generate Allure HTML report
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report